CREATE TYPE user_role AS ENUM ('waiter','bartender','cashier','admin');
CREATE TYPE table_status AS ENUM ('free','occupied','reserved','maintenance');
CREATE TYPE order_status AS ENUM ('open','closed','cancelled');
CREATE TYPE account_status AS ENUM ('pending','paid','refunded');
CREATE TYPE modifier_type AS ENUM ('extra','substitution','discount','preparation');
CREATE TYPE payment_method AS ENUM ('cash','card','transfer','other');

CREATE TABLE "product_categories" (
  "product_category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar
);

CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "name" varchar,
  "role" varchar,
  "email" varchar,
  "password_hash" varchar,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "bar_table" (
  "table_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_number" integer,
  "status" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "provisionalTotal" integer
);

CREATE TABLE "products" (
  "product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer,
  "name" varchar,
  "description" varchar,
  "base_price" numeric,
  "is_active" boolean
);

CREATE TABLE "product_variants" (
  "product_variant_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "name" varchar,
  "price" numeric,
  "volume_ml" integer,
  "is_active" boolean
);

CREATE TABLE "modifiers" (
  "modifier_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "type" varchar,
  "price_adjustment" numeric,
  "is_active" boolean
);

CREATE TABLE "orders" (
  "order_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_id" integer,
  "status" varchar,
  "created_at" timestamp DEFAULT 'now()',
  "closed_at" timestamp
);

CREATE TABLE "order_accounts" (
  "order_account_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer,
  "customer_name" varchar,
  "status" varchar,
  "total" numeric,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "order_items" (
  "order_item_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_account_id" integer,
  "product_variant_id" integer,
  "quantity" integer,
  "unit_price" numeric,
  "discount" numeric,
  "notes" text,
  "product_snapshot" json,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "order_item_modifiers" (
  "order_item_modifier_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_item_id" integer,
  "modifier_id" integer,
  "price_adjustment" numeric
);

CREATE TABLE "waitress_tables" (
  "waitress_table_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "waitress_id" integer,
  "table_id" integer,
  "assigned_at" timestamp DEFAULT 'now()',
  "released_at" timestamp
);

CREATE TABLE "payments" (
  "payment_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_account_id" integer,
  "amount" numeric,
  "method" varchar,
  "reference" varchar,
  "paid_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "product_variant" (
  "product_variant_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "name" varchar,
  "price" numeric,
  "volume_ml" integer,
  "is_active" boolean
)

ALTER TABLE "waitress_tables" ADD FOREIGN KEY ("waitress_id") REFERENCES "users" ("user_id");

ALTER TABLE "waitress_tables" ADD FOREIGN KEY ("table_id") REFERENCES "bar_table" ("table_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("table_id") REFERENCES "bar_table" ("table_id");

ALTER TABLE "order_accounts" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_account_id") REFERENCES "order_accounts" ("order_account_id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "product_categories" ("product_category_id");

ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_variant_id") REFERENCES "product_variants" ("product_variant_id");

ALTER TABLE "order_item_modifiers" ADD FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("order_item_id");

ALTER TABLE "order_item_modifiers" ADD FOREIGN KEY ("modifier_id") REFERENCES "modifiers" ("modifier_id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_account_id") REFERENCES "order_accounts" ("order_account_id");

insert into
  bar_tables (table_number, status, provisionaltotal)
VALUES
(1, 'free',0),
  (2, 'free',0),
  (3, 'free',0),
  (4, 'free',0),
  (5, 'free',0),
  (6, 'free',0),
  (7, 'free',0),
  (8, 'free',0),
(9, 'free',0),
  (10, 'free',0),
  (11, 'free',0),
  (12, 'free',0),
  (13, 'free',0),
  (14, 'free',0),
  (15, 'free',0),
  (16, 'free',0),
(17, 'free',0),
  (18, 'free',0),
  (19, 'free',0),
  (20, 'free',0),
  (21, 'free',0),
  (22, 'free',0),
  (23, 'free',0),
  (24, 'free',0),
  (25, 'free',0),
  (26, 'free',0),
  (27, 'free',0),
  (28, 'free',0),
  (29, 'free',0),
  (30, 'free',0),
  (31, 'free',0),
   (32, 'free',0),
   (33, 'free',0),
  (34, 'free',0),
  (35, 'free',0),
  (36, 'free',0),
(37, 'free',0),
  (38, 'free',0),
  (39, 'free',0),
  (40, 'free',0),
  (41, 'free',0),
  (4, 'free',0),
  (43, 'free',0),
  (44, 'free',0),
  (45, 'free',0);
   
insert into products (name, description, category_id, base_price, is_active)
values 
('Shot C.Plata','Pending',3,70,true),
('Shot C.Reposad','Pending',3,70,true),
('Shot Sauza','Pending',3,70,true),
('Shot Hornitos','Pending',3,80,true),
('Shot H.de Tepa','Pending',3,80,true),
('Shot H.Plata','Pending',3,120,true),
('Shot H.Reposado','Pending',3,150,true),
('Shot M.Dobel','Pending',3,150,true),
('Shot 1800','Pending',3,160,true),
('Shot Don Julio','Pending',3,200,true),
('Shot H. Ultra','Pending',3,160,true),
('Cuba C.Plata','Pending',3,100,true),
('Cuba C.Reposad','Pending',3,100,true),
('Cuba Sauza','Pending',3,100,true),
('Cuba Hornitos','Pending',3,120,true),
('Cuba H.de Tepa','Pending',3,120,true),
('Cuba H.Plata','Pending',3,140,true),
('Cuba H.Reposado','Pending',3,170,true),
('Cuba M.Dobel','Pending',3,170,true),
('Cuba 1800','Pending',3,180,true),
('Cuba Don Julio','Pending',3,200,true),
('Cuba H. Ultra','Pending',3,180,true);

insert into products (name, description, category_id, base_price, is_active)
values 
('Mojito Frutos Rojos','Pending',6,120,true),
('Mojito Natural','Pending',6,120,true),
('Mojito Mango','Pending',6,120,true),
('Cubanito','Pending',6,120,true),
('Bomba','Pending',6,120,true),
('Mezcal grande','Pending',6,120,true),
('Mezcal Chico','Pending',6,60,true),
('Piña Colada','Pending',6,80,true),
('Vampiro','Pending',6,150,true),
('Paloma C.Plata','Pending',6,100,true),
('Perla Negra','Pending',6,90,true);
insert into products (name, description, category_id, base_price, is_active)
VALUES
('Corona','Pending',1,40,true),
('Victoria','Pending',1,40,true),
('Cubeta','Pending',1,240,true),
('Litro de cerveza','Pending',1,100,true);

insert into products (name, description, category_id, base_price, is_active)
VALUES
('Michelada Corona Ch','Pending',2,60,true),
('Michelada Victoria Ch','Pending',2,60,true),
('Michelada Corona G','Pending',2,120,true),
('Michelada Victoria G','Pending',2,120,true),
('Gringa Corona Ch','Pending',2,60,true),
('Gringa Victoria Ch','Pending',2,60,true),
('Gringa Corona G','Pending',2,120,true),
('Gringa Victoria G','Pending',2,120,true),
('Preparada Corona Ch','Pending',2,50,true),
('Preparada Victoria Ch','Pending',2,50,true),
('Preparada Corona G','Pending',2,100,true),
('Preparada Victoria G','Pending',2,100,true),
('Chelada Corona Ch','Pending',2,50,true),
('Chelada Victoria Ch','Pending',2,50,true),
('Chelada Corona G','Pending',2,100,true),
('Chelada Victoria G','Pending',2,100,true);

insert into products (name, description, category_id, base_price, is_active)
values 
('Servicio C.Plata','Pending',4,1000,true),
('Servicio C.Reposad','Pending',4,1000,true),
('Servicio Sauza','Pending',4,1000,true),
('Servicio Hornitos','Pending',4,1200,true),
('Servicio H.de Tepa','Pending',4,1000,true),
('Servicio H.Plata','Pending',4,1500,true),
('Servicio H.Reposado','Pending',4,1800,true),
('Servicio M.Dobel','Pending',4,1900,true),
('Servicio 1800','Pending',4,2000,true),
('Servicio Don Julio','Pending',4,2500,true),
('Servicio H. Ultra','Pending',4,2000,true);

insert into products (name, description, category_id, base_price, is_active)
values 
('Rusa','Pending',5,40,true),
('Limonada','Pending',5,40,true),
('Naranjada','Pending',5,40,true),
('Agua natural','Pending',5,20,true),
('Refresco/Agua mineral','Pending',5,25,true),
('Michelada Falsa','Pending',5,80,true);

insert into products (name, description, category_id, base_price, is_active)
values 
('Cuba Absolut','Pending',7,180,true),
('Cuba Black Label','Pending',7,180,true),
('Cuba Red Label','Pending',7,180,true),
('Cuba Buchanas','Pending',7,180,true);

insert into product_categories (name, description)
values 
('Cerveza','Pending'),
('Preparados de cerveza','Pending'),
('Tequila','Pending'),
('Servicios','Pending'),
('Sin alcohol','Pending'),
('Cocteleria','Pending'),
('Varios','Pending');
